comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

language: R
sudo: false
cache: packages
after_success:
  - Rscript -e 'covr::codecov()'
